<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/16 02:41:18

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bigorange',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
